# fly.toml app configuration file generated for scholarship-scraper-red-bush-3064 on 2025-03-14T08:33:32-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'scholarship-scraper-red-bush-3064'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source="database"
  destination="/mnt/database"